#!/bin/sh

if [ $# -lt 1 ]
then
  echo "Usage: $0 <device>"
  exit 1
fi

hdd=$1

echo "Start preparing for $hdd"

sgdisk -Z "$hdd"
sgdisk -n 0:0:+512MiB -t 0:ef00 -c 0:"EFI System Partition" "$hdd"
sgdisk -n 0:0:+4096MiB -t 0:8200 -c 0:"Linux Swap Partition" "$hdd"
sgdisk -n 0:0:0 -t 0:8300 -c 0:"Linux Filesystem" "$hdd"
sgdisk -p "$hdd"

mkswap "${hdd}2"
swapon "${hdd}2"

mkfs.vfat -F32 "${hdd}1"

mkfs.btrfs -L tank "${hdd}3"

mount -o relatime,compress=zstd,space_cache=v2,autodefrag "${hdd}3" /mnt

btrfs subvolume create /mnt/@
btrfs subvolume create /mnt/@root
btrfs subvolume create /mnt/@home
btrfs subvolume create /mnt/@pkg
btrfs subvolume create /mnt/@log
btrfs subvolume create /mnt/@snapshots

umount /mnt

mount -o relatime,compress=zstd,space_cache=v2,autodefrag,subvol=@root "${hdd}3" /mnt
mkdir -p /mnt/{.snapshots,boot,home,var/log,var/cache/pacman/pkg}
mount -o relatime,compress=zstd,space_cache=v2,autodefrag,subvol=@home "${hdd}3" /mnt/home
mount -o relatime,compress=zstd,space_cache=v2,autodefrag,subvol=@log "${hdd}3" /mnt/var/log
mount -o relatime,compress=zstd,space_cache=v2,autodefrag,subvol=@pkg "${hdd}3" /mnt/var/cache/pacman/pkg
mount -o relatime,compress=zstd,space_cache=v2,autodefrag,subvol=@snapshots "${hdd}3" /mnt/.snapshots

mount /dev/sda1 /mnt/boot

#sda1_UUID=`lsblk -rno UUID /dev/sda1`
#sda2_UUID=`lsblk -rno UUID /dev/sda2`
#sda3_UUID=`lsblk -rno UUID /dev/sda3`

sda1_UUID=`lsblk -rno UUID ${hdd}1`
sda2_UUID=`lsblk -rno UUID ${hdd}2`
sda3_UUID=`lsblk -rno UUID ${hdd}3`

cat >../fstab_text <<EOT
UUID=${sda3_UUID}	/	btrfs	relatime,compress=zstd,space_cache=v2,autodefrag,subvol=@root	0	0
UUID=${sda3_UUID}	/home	btrfs	relatime,compress=zstd,space_cache=v2,autodefrag,subvol=@home	0	0
UUID=${sda3_UUID}	/var/log	btrfs	relatime,compress=zstd,space_cache=v2,autodefrag,subvol=@log	0	0
UUID=${sda3_UUID}	/var/cache/pacman/pkg	btrfs	relatime,compress=zstd,space_cache=v2,autodefrag,subvol=@pkg	0	0
UUID=${sda3_UUID}	/.snapshots	btrfs	relatime,compress=zstd,space_cache=v2,autodefrag,subvol=@snapshots	0	0
UUID=${sda2_UUID}	none	swap	defaults	0	0
UUID=${sda1_UUID}	/boot	vfat	relatime,fmask=0022,dmask=0022,codepage=437,iocharset=iso8859-1,shortname=mixed,errors=remount-ro	0	2
EOT
