#!/bin/bash
set -e

echo "Start running $(basename $0)"

echo '
[archlinuxfr]
SigLevel = Never
Server = http://repo.archlinux.fr/$arch' | sudo tee --append /etc/pacman.conf > /dev/null

echo "End running $(basename $0)"
