#!/bin/bash
set -e

echo "Start running $(basename $0)"

sudo pacman -S arc-gtk-theme noto-fonts --needed --noconfirm

sudo mkdir /home/.anyfiles
sudo chown root:users /home/.anyfiles
sudo chmod 755 /home/.anyfiles

sudo cp ./images/archlinux-128x128.png /home/.anyfiles
sudo mv /etc/lightdm/lightdm-gtk-greeter.conf /etc/lightdm/lightdm-gtk-greeter.conf.bak
sudo cp ./files/lightdm-gtk-greeter.conf /etc/lightdm/lightdm-gtk-greeter.conf

echo "End running $(basename $0)"
