#!/bin/bash
set -e

echo "Start running $(basename $0)"

# install base
pkgs="openbox obconf obmenu openbox-themes"
./999-install-software-arch-linux-repo "$pkgs"

# intall tools and ...
pkgs="lxappearance lxappearance-obconf"
./999-install-software-arch-linux-repo "$pkgs"

# install themes, cursor and ...
pkgs="arc-icon-theme xcursor-simpleandsoft"
./999-install-software-arch-linux-repo "$pkgs"

echo "End running $(basename $0)"
